# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  verify_formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Restore swiftformat build cache
      uses: actions/cache@v3
      with:
        path: .build/release/swiftformat
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build swiftformat
      run: |
        if [ ! -f ".build/release/swiftformat" ]; then
          swift build --product swiftformat -c release
        fi

    - name: Run swiftformat
      run: .build/release/swiftformat --verbose .

    - name: Verify that formatted code is unchanged
      run: git diff --exit-code HEAD


  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: swift build
    
    - name: Run tests
      run: swift test
